"""baseline schema

Revision ID: 51457bd3ae41
Revises: 
Create Date: 2026-09-22 14:15:40.028958
"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '51457bd3ae41'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('approvals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('request_key', sa.String(length=128), nullable=False),
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.Column('payload_json', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('responded_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('responder_id', sa.String(length=64), nullable=True),
    sa.Column('response_note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('request_key')
    )
    op.create_table('audit_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_type', sa.String(length=48), nullable=False),
    sa.Column('actor', sa.String(length=32), nullable=False),
    sa.Column('symbol', sa.String(length=16), nullable=True),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('detail_json', sa.Text(), nullable=True),
    sa.Column('trading_mode', sa.String(length=8), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('audit_log', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audit_log_event_type'), ['event_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_log_symbol'), ['symbol'], unique=False)

    op.create_table('compliance_screens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(length=16), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('source', sa.String(length=64), nullable=False),
    sa.Column('screened_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ratio_denominator', sa.String(length=16), nullable=True),
    sa.Column('debt_ratio', sa.Float(), nullable=True),
    sa.Column('interest_securities_ratio', sa.Float(), nullable=True),
    sa.Column('non_permissible_revenue_ratio', sa.Float(), nullable=True),
    sa.Column('business_activity_flags', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('raw_response_json', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('compliance_screens', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_compliance_screens_screened_at'), ['screened_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_compliance_screens_symbol'), ['symbol'], unique=False)
        batch_op.create_index('ix_screens_symbol_time', ['symbol', 'screened_at'], unique=False)

    op.create_table('dividends',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(length=16), nullable=False),
    sa.Column('pay_date', sa.Date(), nullable=False),
    sa.Column('gross_amount', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('non_permissible_ratio', sa.Float(), nullable=True),
    sa.Column('purification_due', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('ratio_source', sa.String(length=64), nullable=True),
    sa.Column('purified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('symbol', 'pay_date', name='uq_dividend_symbol_date')
    )
    with op.batch_alter_table('dividends', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_dividends_pay_date'), ['pay_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_dividends_symbol'), ['symbol'], unique=False)

    op.create_table('equity_snapshots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('snapshot_date', sa.Date(), nullable=False),
    sa.Column('taken_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('equity', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('cash_settled', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('cash_unsettled', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('positions_value', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('day_pnl', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('open_positions', sa.Integer(), nullable=False),
    sa.Column('trading_mode', sa.String(length=8), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('snapshot_date')
    )
    op.create_table('setting_overrides',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=128), nullable=False),
    sa.Column('value_json', sa.Text(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_by', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key')
    )
    op.create_table('signals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(length=16), nullable=False),
    sa.Column('strategy', sa.String(length=64), nullable=False),
    sa.Column('as_of_date', sa.Date(), nullable=False),
    sa.Column('side', sa.String(length=8), nullable=False),
    sa.Column('score', sa.Float(), nullable=True),
    sa.Column('probability', sa.Float(), nullable=True),
    sa.Column('expected_return_low', sa.Float(), nullable=True),
    sa.Column('expected_return_high', sa.Float(), nullable=True),
    sa.Column('suggested_holding_days', sa.Integer(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('disposition', sa.String(length=32), nullable=False),
    sa.Column('disposition_reason', sa.Text(), nullable=True),
    sa.Column('features_json', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('signals', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_signals_as_of_date'), ['as_of_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_signals_symbol'), ['symbol'], unique=False)
        batch_op.create_index('ix_signals_symbol_date', ['symbol', 'as_of_date'], unique=False)

    op.create_table('trades',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(length=16), nullable=False),
    sa.Column('strategy', sa.String(length=64), nullable=False),
    sa.Column('side', sa.String(length=8), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=18, scale=8), nullable=False),
    sa.Column('entry_price', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('entry_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('entry_date', sa.Date(), nullable=False),
    sa.Column('exit_price', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('exit_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('exit_date', sa.Date(), nullable=True),
    sa.Column('exit_reason', sa.String(length=32), nullable=True),
    sa.Column('stop_loss_price', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('take_profit_price', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('gross_pnl', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('costs_paid', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('net_pnl', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('holding_trading_days', sa.Integer(), nullable=True),
    sa.Column('compliance_status_at_entry', sa.String(length=16), nullable=False),
    sa.Column('compliance_source_at_entry', sa.String(length=64), nullable=False),
    sa.Column('compliance_screened_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('trading_mode', sa.String(length=8), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('trades', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_trades_entry_date'), ['entry_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_trades_symbol'), ['symbol'], unique=False)

    op.create_table('orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('idempotency_key', sa.String(length=128), nullable=False),
    sa.Column('broker_order_id', sa.String(length=64), nullable=True),
    sa.Column('symbol', sa.String(length=16), nullable=False),
    sa.Column('side', sa.String(length=8), nullable=False),
    sa.Column('order_type', sa.String(length=16), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=18, scale=8), nullable=False),
    sa.Column('is_fractional', sa.Boolean(), nullable=False),
    sa.Column('limit_price', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('stop_price', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('take_profit_price', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('stop_is_synthetic', sa.Boolean(), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('filled_quantity', sa.Numeric(precision=18, scale=8), nullable=False),
    sa.Column('filled_avg_price', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('filled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('signal_id', sa.Integer(), nullable=True),
    sa.Column('rejection_reason', sa.Text(), nullable=True),
    sa.Column('trading_mode', sa.String(length=8), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['signal_id'], ['signals.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('idempotency_key')
    )
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_orders_broker_order_id'), ['broker_order_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_orders_symbol'), ['symbol'], unique=False)

    op.create_table('settlement_entries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(length=16), nullable=False),
    sa.Column('amount', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('sold_on', sa.Date(), nullable=False),
    sa.Column('settles_on', sa.Date(), nullable=False),
    sa.Column('settled', sa.Boolean(), nullable=False),
    sa.Column('trade_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['trade_id'], ['trades.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('settlement_entries', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_settlement_entries_settles_on'), ['settles_on'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('settlement_entries', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_settlement_entries_settles_on'))

    op.drop_table('settlement_entries')
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_orders_symbol'))
        batch_op.drop_index(batch_op.f('ix_orders_broker_order_id'))

    op.drop_table('orders')
    with op.batch_alter_table('trades', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_trades_symbol'))
        batch_op.drop_index(batch_op.f('ix_trades_entry_date'))

    op.drop_table('trades')
    with op.batch_alter_table('signals', schema=None) as batch_op:
        batch_op.drop_index('ix_signals_symbol_date')
        batch_op.drop_index(batch_op.f('ix_signals_symbol'))
        batch_op.drop_index(batch_op.f('ix_signals_as_of_date'))

    op.drop_table('signals')
    op.drop_table('setting_overrides')
    op.drop_table('equity_snapshots')
    with op.batch_alter_table('dividends', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_dividends_symbol'))
        batch_op.drop_index(batch_op.f('ix_dividends_pay_date'))

    op.drop_table('dividends')
    with op.batch_alter_table('compliance_screens', schema=None) as batch_op:
        batch_op.drop_index('ix_screens_symbol_time')
        batch_op.drop_index(batch_op.f('ix_compliance_screens_symbol'))
        batch_op.drop_index(batch_op.f('ix_compliance_screens_screened_at'))

    op.drop_table('compliance_screens')
    with op.batch_alter_table('audit_log', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_log_symbol'))
        batch_op.drop_index(batch_op.f('ix_audit_log_event_type'))

    op.drop_table('audit_log')
    op.drop_table('approvals')
    # ### end Alembic commands ###
