"""strategy track records

Revision ID: 1a36d52922cd
Revises: 51457bd3ae41
Create Date: 2026-09-23 12:47:08.985479
"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '1a36d52922cd'
down_revision: str | None = '51457bd3ae41'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('strategy_track_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('strategy', sa.String(length=64), nullable=False),
    sa.Column('measured_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('period_start', sa.Date(), nullable=True),
    sa.Column('period_end', sa.Date(), nullable=True),
    sa.Column('trades', sa.Integer(), nullable=False),
    sa.Column('win_rate', sa.Float(), nullable=True),
    sa.Column('avg_return', sa.Float(), nullable=True),
    sa.Column('sharpe', sa.Float(), nullable=True),
    sa.Column('out_of_sample', sa.Boolean(), nullable=False),
    sa.Column('source', sa.String(length=64), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('strategy_track_records', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_strategy_track_records_strategy'), ['strategy'], unique=False)
        batch_op.create_index('ix_track_record_strategy_measured', ['strategy', 'measured_at'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('strategy_track_records', schema=None) as batch_op:
        batch_op.drop_index('ix_track_record_strategy_measured')
        batch_op.drop_index(batch_op.f('ix_strategy_track_records_strategy'))

    op.drop_table('strategy_track_records')
    # ### end Alembic commands ###
